const {
  modelNumberMaxChar,
  modelNumberMinChar,
  motorNameMaxChar,
  motorNameMinChar,
  manufacturerMaxChar,
  manufacturerMinChar,
  powerHpMaxNum,
  powerHpMinNum,
  powerKwMaxNum,
  powerKwMinNum,
  rpmMinNum,
  rpmMaxNum,
  frameSizeMaxChar,
  frameSizeMinChar,
  fullLoadCurrentMinNum,
  fullLoadCurrentMaxNum,
  startingCurrentMaxNum,
  startingCurrentMinNum,
  torqueNmMaxNum,
  torqueNmMinNum,
  powerFactorMinNum,
  powerFactorMaxNum,
  efficiencyPercentMinNum,
  efficiencyPercentMaxNum,
  weightKgMinNum,
  weightKgMaxNum,
  noiseLevelDbMinNum,
  noiseLevelDbMaxNum,
  shaftDiameterNmMaxNum,
  shaftDiameterNmMinNum,
  shaftLengthNmMinNum,
  shaftLengthNmMaxNum,
  overallLengthNmMinNum,
  overallLengthNmMaxNum,
  heightNmMinNum,
  heightNmMaxNum,
  widthNmMinNum,
  widthNmMaxNum,
  flangeDiameterNmMinNum,
  flangeDiameterNmMaxNum,
  boltHoleDistanceNmMinNum,
  boltHoleDistanceNmMaxNum,
  footMountHoleDistanceNmMinNum,
  footMountHoleDistanceNmMaxNum,
  dataSheetURLMaxChar,
  dataSheetURLMinChar,
  imageURLMaxChar,
  imageURLMinChar,
} = require("@Helpers/validationConst");

const motorValidationMessage = {
  modelNumberRequired: "Model number is required",
  modelNumberMaxLength: `Model number length must be at most ${modelNumberMaxChar} characters`,
  modelNumberMinLength: `Model number length must be at least ${modelNumberMinChar} characters`,
  motorNameRequired: "Motor name is required",
  motorNameMaxLength: `Motor name length must be at most ${motorNameMaxChar} characters`,
  motorNameMinLength: `Motor name length must be at least ${motorNameMinChar} characters`,
  categoryInvalid: "Invalid motor category",
  categoryRequired: "Motor category is required",
  manufacturerMaxLength: `Manufacturer length must be at most ${manufacturerMaxChar} characters`,
  manufacturerMinLength: `Manufacturer length must be at least ${manufacturerMinChar} characters`,
  powerHpRequired: "Power (HP) is required",
  powerHpMaxLength: `Power (HP) must be at most ${powerHpMaxNum} number`,
  powerHpMinLength: `Power (HP) must be at least ${powerHpMinNum} number`,
  powerKwRequired: "Power (kW) is required",
  powerKwMaxLength: `Power (kW) must be at most ${powerKwMaxNum} number`,
  powerKwMinLength: `Power (kW) must be at least ${powerKwMinNum} number`,
  polesInvalid: "Invalid pole count",
  polesRequired: "Pole count is required",
  rpmMaxLength: `RPM must be at most ${rpmMaxNum} number`,
  rpmMinLength: `RPM must be at least ${rpmMinNum} number`,
  phaseInvalid: "Invalid phase",
  phaseRequired: "Phase is required",
  voltageRequired: "Voltage is required",
  voltageInvalid: "Invalid voltage rating",
  frequencyInvalid: "Invalid frequency",
  frequencyRequired: "Frequency is required",
  frameSizeMaxLength: `Frame size length must be at most ${frameSizeMaxChar} characters`,
  frameSizeMinLength: `Frame size length must be at least ${frameSizeMinChar} characters`,
  mountingTypeInvalid: "Invalid mounting type",
  efficiencyClassInvalid: "Invalid efficiency class",
  insulationClassInvalid: "Invalid insulation class",
  protectionInvalid: "Invalid protection rating",
  fullLoadCurrentMaxLength: `Full load current must be at most ${fullLoadCurrentMaxNum} number`,
  fullLoadCurrentMinLength: `Full load current must be at least ${fullLoadCurrentMinNum} number`,
  startingCurrentMaxLength: `Starting current must be at most ${startingCurrentMaxNum} number`,
  startingCurrentMinLength: `Starting current must be at least ${startingCurrentMinNum} number`,
  startingMethodInvalid: "Invalid starting method",
  torqueNMMaxLength: `Torque (Nm) must be at most ${torqueNmMaxNum} number`,
  torqueNMMinLength: `Torque (Nm) must be at least ${torqueNmMinNum} number`,
  powerFactorMaxLength: `Power factor must be at most ${powerFactorMaxNum} number`,
  powerFactorMinLength: `Power factor must be at least ${powerFactorMinNum} number`,
  efficiencyPercentMaxLength: `Efficiency percent must be at most ${efficiencyPercentMaxNum} number`,
  efficiencyPercentMinLength: `Efficiency percent must be at least ${efficiencyPercentMinNum} number`,
  weightKgMaxLength: `Weight (kg) must be at most ${weightKgMaxNum} number`,
  weightKgMinLength: `Weight (kg) must be at least ${weightKgMinNum} number`,
  noiseLevelDbMaxLength: `Noise level (dB) must be at most ${noiseLevelDbMaxNum} number`,
  noiseLevelDbMinLength: `Noise level (dB) must be at least ${noiseLevelDbMinNum} number`,
  shaftDiameterNMMaxLength: `Shaft diameter (mm) must be at most ${shaftDiameterNmMaxNum} number`,
  shaftDiameterNMMinLength: `Shaft diameter (mm) must be at least ${shaftDiameterNmMinNum} number`,
  shaftLengthNMMaxLength: `Shaft length (mm) must be at most ${shaftLengthNmMaxNum} number`,
  shaftLengthNMMinLength: `Shaft length (mm) must be at least ${shaftLengthNmMinNum} number`,
  overallLengthNMMaxLength: `Overall length (mm) must be at most ${overallLengthNmMaxNum} number`,
  overallLengthNMMinLength: `Overall length (mm) must be at least ${overallLengthNmMinNum} number`,
  heightNMMaxLength: `Height (mm) must be at most ${heightNmMaxNum} number`,
  heightNMMinLength: `Height (mm) must be at least ${heightNmMinNum} number`,
  widthNMMaxLength: `Width (mm) must be at most ${widthNmMaxNum} number`,
  widthNMMinLength: `Width (mm) must be at least ${widthNmMinNum} number`,
  flangeDiameterNMMaxLength: `Flange diameter (mm) must be at most ${flangeDiameterNmMaxNum} number`,
  flangeDiameterNMMinLength: `Flange diameter (mm) must be at least ${flangeDiameterNmMinNum} number`,
  boltHoleDistanceNMMaxLength: `Bolt hole distance (mm) must be at most ${boltHoleDistanceNmMaxNum} number`,
  boltHoleDistanceNMMinLength: `Bolt hole distance (mm) must be at least ${boltHoleDistanceNmMinNum} number`,
  footMountHoleDistanceNMMaxLength: `Foot mount hole distance (mm) must be at most ${footMountHoleDistanceNmMaxNum} number`,
  footMountHoleDistanceNMMinLength: `Foot mount hole distance (mm) must be at least ${footMountHoleDistanceNmMinNum} number`,
  imageURLMaxLength: `Image URL length must be at most ${imageURLMaxChar} characters`,
  imageURLMinLength: `Image URL length must be at least ${imageURLMinChar} characters`,
  dataSheetURLMaxLength: `Data sheet URL length must be at most ${dataSheetURLMaxChar} characters`,
  dataSheetURLMinLength: `Data sheet URL length must be at least ${dataSheetURLMinChar} characters`,
};

module.exports = motorValidationMessage;
