const mongoose = require("mongoose");

const { Schema } = mongoose;

const {
  MOTOR_PHASE,
  MOTOR_CATEGORY,
  MOTOR_FREQUENCY,
  MOTOR_POLE_COUNT,
  MOTOR_MANUFACTURER,
  MOTOR_MOUNTING_TYPE,
  MOTOR_VOLTAGE_RATING,
  MOTOR_STARTING_METHOD,
  MOTOR_EFFICIENCY_CLASS,
  MOTOR_INSULATION_CLASS,
  MOTOR_PROTECTION_RATING,
} = require("@Helpers/enums");

const {
  modelNumberRequired,
  modelNumberMaxLength,
  modelNumberMinLength,
  motorNameRequired,
  motorNameMaxLength,
  motorNameMinLength,
  categoryInvalid,
  categoryRequired,
  manufacturerMaxLength,
  manufacturerMinLength,
  powerHpRequired,
  powerHpMaxLength,
  powerHpMinLength,
  powerKwRequired,
  powerKwMaxLength,
  powerKwMinLength,
  polesInvalid,
  polesRequired,
  rpmMaxLength,
  rpmMinLength,
  phaseInvalid,
  phaseRequired,
  voltageRequired,
  voltageInvalid,
  frequencyInvalid,
  frequencyRequired,
  frameSizeMaxLength,
  frameSizeMinLength,
  mountingTypeInvalid,
  efficiencyClassInvalid,
  insulationClassInvalid,
  protectionInvalid,
  fullLoadCurrentMinLength,
  fullLoadCurrentMaxLength,
  startingCurrentMaxLength,
  startingCurrentMinLength,
  torqueNMMinLength,
  torqueNMMaxLength,
  powerFactorMinLength,
  powerFactorMaxLength,
  efficiencyPercentMinLength,
  efficiencyPercentMaxLength,
  weightKgMinLength,
  weightKgMaxLength,
  noiseLevelDbMinLength,
  noiseLevelDbMaxLength,
  shaftDiameterNMMaxLength,
  shaftDiameterNMMinLength,
  shaftLengthNMMinLength,
  shaftLengthNMMaxLength,
  overallLengthNMMinLength,
  overallLengthNMMaxLength,
  heightNMMaxLength,
  heightNMMinLength,
  widthNMMaxLength,
  widthNMMinLength,
  flangeDiameterNMMaxLength,
  flangeDiameterNMMinLength,
  boltHoleDistanceNMMaxLength,
  boltHoleDistanceNMMinLength,
  footMountHoleDistanceNMMaxLength,
  footMountHoleDistanceNMMinLength,
  imageURLMaxLength,
  imageURLMinLength,
  dataSheetURLMaxLength,
  dataSheetURLMinLength,
  usernameRequired,
} = require("@Helpers/validationMessage");

const {
  modelNumberMinChar,
  modelNumberMaxChar,
  motorNameMaxChar,
  motorNameMinChar,
  manufacturerMaxChar,
  manufacturerMinChar,
  powerHpMaxNum,
  powerHpMinNum,
  powerKwMaxNum,
  powerKwMinNum,
  rpmMaxNum,
  rpmMinNum,
  frameSizeMinChar,
  frameSizeMaxChar,
  fullLoadCurrentMinNum,
  fullLoadCurrentMaxNum,
  startingCurrentMaxNum,
  startingCurrentMinNum,
  torqueNmMaxNum,
  torqueNmMinNum,
  powerFactorMinNum,
  powerFactorMaxNum,
  efficiencyPercentMinNum,
  efficiencyPercentMaxNum,
  weightKgMinNum,
  weightKgMaxNum,
  noiseLevelDbMinNum,
  noiseLevelDbMaxNum,
  shaftDiameterNmMaxNum,
  shaftDiameterNmMinNum,
  shaftLengthNmMinNum,
  shaftLengthNmMaxNum,
  overallLengthNmMinNum,
  overallLengthNmMaxNum,
  heightNmMinNum,
  heightNmMaxNum,
  widthNmMinNum,
  widthNmMaxNum,
  flangeDiameterNmMinNum,
  flangeDiameterNmMaxNum,
  boltHoleDistanceNmMinNum,
  boltHoleDistanceNmMaxNum,
  footMountHoleDistanceNmMinNum,
  footMountHoleDistanceNmMaxNum,
  imageURLMaxChar,
  imageURLMinChar,
  dataSheetURLMaxChar,
  dataSheetURLMinChar,
} = require("@Helpers/validationConst");

const motorSchema = Schema(
  {
    model_number: {
      type: String,
      required: [true, modelNumberRequired],
      unique: true,
      minlength: [modelNumberMinChar, modelNumberMinLength],
      maxlength: [modelNumberMaxChar, modelNumberMaxLength],
      trim: true,
    },
    motor_name: {
      type: String,
      required: [true, motorNameRequired],
      minlength: [motorNameMinChar, motorNameMinLength],
      maxlength: [motorNameMaxChar, motorNameMaxLength],
      trim: true,
    },
    category: {
      type: String,
      required: [true, categoryRequired],
      enum: {
        values: [
          MOTOR_CATEGORY.SINGLE_PHASE,
          MOTOR_CATEGORY.THREE_PHASE,
          MOTOR_CATEGORY.FLAMEPROOF,
          MOTOR_CATEGORY.INDUCTION_MOTOR,
          MOTOR_CATEGORY.BRAKE_MOTOR,
          MOTOR_CATEGORY.INVERTER_DUTY,
          MOTOR_CATEGORY.CUSTOM,
        ],
        message: categoryInvalid,
      },
    },
    manufacturer: {
      type: String,
      default: MOTOR_MANUFACTURER.CG,
      minlength: [manufacturerMinChar, manufacturerMinLength],
      maxlength: [manufacturerMaxChar, manufacturerMaxLength],
    },
    basic_details: {
      power_hp: {
        type: Number,
        required: [true, powerHpRequired],
        min: [powerHpMinNum, powerHpMinLength],
        max: [powerHpMaxNum, powerHpMaxLength],
      },
      power_kw: {
        type: Number,
        required: [true, powerKwRequired],
        min: [powerKwMinNum, powerKwMinLength],
        max: [powerKwMaxNum, powerKwMaxLength],
      },
      poles: {
        type: Number,
        required: [true, polesRequired],
        enum: {
          values: [
            MOTOR_POLE_COUNT.TWO_POLE,
            MOTOR_POLE_COUNT.FOUR_POLE,
            MOTOR_POLE_COUNT.SIX_POLE,
            MOTOR_POLE_COUNT.EIGHT_POLE,
          ],
          message: polesInvalid,
        },
      },
      rpm: {
        type: Number,
        min: [rpmMinNum, rpmMinLength],
        max: [rpmMaxNum, rpmMaxLength],
      },
      phase: {
        type: String,
        enum: {
          values: [MOTOR_PHASE.SINGLE_PHASE, MOTOR_PHASE.THREE_PHASE],
          message: phaseInvalid,
        },
        required: [true, phaseRequired],
      },
      voltage: {
        type: String,
        required: [true, voltageRequired],
        enum: {
          values: [
            MOTOR_VOLTAGE_RATING.V_230,
            MOTOR_VOLTAGE_RATING.V_415,
            MOTOR_VOLTAGE_RATING.V_110,
            MOTOR_VOLTAGE_RATING.V_440,
          ],
          message: voltageInvalid,
        },
      },
      frequency: {
        type: Number,
        required: [true, frequencyRequired],
        enum: {
          values: [MOTOR_FREQUENCY.FREQ_50HZ, MOTOR_FREQUENCY.FREQ_60HZ],
          message: frequencyInvalid,
        },
      },
      frame_size: {
        type: String,
        minlength: [frameSizeMinChar, frameSizeMinLength],
        maxlength: [frameSizeMaxChar, frameSizeMaxLength],
      },
      mounting_type: {
        type: String,
        enum: {
          values: [
            MOTOR_MOUNTING_TYPE.B3,
            MOTOR_MOUNTING_TYPE.B5,
            MOTOR_MOUNTING_TYPE.B35,
            MOTOR_MOUNTING_TYPE.B14,
            MOTOR_MOUNTING_TYPE.FOOT_MOUNTED,
            MOTOR_MOUNTING_TYPE.FLANGE_MOUNTED,
          ],
          message: mountingTypeInvalid,
        },
      },
      efficiency_class: {
        type: String,
        enum: {
          values: [
            MOTOR_EFFICIENCY_CLASS.IE1,
            MOTOR_EFFICIENCY_CLASS.IE2,
            MOTOR_EFFICIENCY_CLASS.IE3,
            MOTOR_EFFICIENCY_CLASS.IE4,
            MOTOR_EFFICIENCY_CLASS.STANDARD,
          ],
          message: efficiencyClassInvalid,
        },
      },
      insulation_class: {
        type: String,
        enum: {
          values: [
            MOTOR_INSULATION_CLASS.A,
            MOTOR_INSULATION_CLASS.B,
            MOTOR_INSULATION_CLASS.F,
            MOTOR_INSULATION_CLASS.H,
          ],
          message: insulationClassInvalid,
        },
      },
      protection: {
        type: String,
        enum: {
          values: [
            MOTOR_PROTECTION_RATING.IP_44,
            MOTOR_PROTECTION_RATING.IP_55,
            MOTOR_PROTECTION_RATING.IP_56,
            MOTOR_PROTECTION_RATING.IP_65,
          ],
          message: protectionInvalid,
        },
      },
    },
    technical_specs: {
      full_load_current: {
        type: Number,
        min: [fullLoadCurrentMinNum, fullLoadCurrentMinLength],
        max: [fullLoadCurrentMaxNum, fullLoadCurrentMaxLength],
      },
      starting_current: {
        type: Number,
        min: [startingCurrentMinNum, startingCurrentMinLength],
        max: [startingCurrentMaxNum, startingCurrentMaxLength],
      },
      starting_method: {
        type: String,
        enum: {
          values: [
            MOTOR_STARTING_METHOD.DOL,
            MOTOR_STARTING_METHOD.STAR_DELTA,
            MOTOR_STARTING_METHOD.VFD,
            MOTOR_STARTING_METHOD.SOFT_STARTER,
          ],
          message: startingMethodInvalid,
        },
      },
      torque_nm: {
        type: Number,
        min: [torqueNmMinNum, torqueNMMinLength],
        max: [torqueNmMaxNum, torqueNMMaxLength],
      },
      power_factor: {
        type: Number,
        min: [powerFactorMinNum, powerFactorMinLength],
        max: [powerFactorMaxNum, powerFactorMaxLength],
      },
      efficiency_percent: {
        type: Number,
        min: [efficiencyPercentMinNum, efficiencyPercentMinLength],
        max: [efficiencyPercentMaxNum, efficiencyPercentMaxLength],
      },
      weight_kg: {
        type: Number,
        min: [weightKgMinNum, weightKgMinLength],
        max: [weightKgMaxNum, weightKgMaxLength],
      },
      noise_level_db: {
        type: Number,
        min: [noiseLevelDbMinNum, noiseLevelDbMinLength],
        max: [noiseLevelDbMaxNum, noiseLevelDbMaxLength],
      },
    },
    dimensions: {
      shaft_diameter_mm: {
        type: Number,
        min: [shaftDiameterNmMinNum, shaftDiameterNMMinLength],
        max: [shaftDiameterNmMaxNum, shaftDiameterNMMaxLength],
      },
      shaft_length_mm: {
        type: Number,
        min: [shaftLengthNmMinNum, shaftLengthNMMinLength],
        max: [shaftLengthNmMaxNum, shaftLengthNMMaxLength],
      },
      overall_length_mm: {
        type: Number,
        min: [overallLengthNmMinNum, overallLengthNMMinLength],
        max: [overallLengthNmMaxNum, overallLengthNMMaxLength],
      },
      height_mm: {
        type: Number,
        min: [heightNmMinNum, heightNMMinLength],
        max: [heightNmMaxNum, heightNMMaxLength],
      },
      width_mm: {
        type: Number,
        min: [widthNmMinNum, widthNMMinLength],
        max: [widthNmMaxNum, widthNMMaxLength],
      },
      flange_diameter_mm: {
        type: Number,
        min: [flangeDiameterNmMinNum, flangeDiameterNMMinLength],
        max: [flangeDiameterNmMaxNum, flangeDiameterNMMaxLength],
      },
      bolt_hole_distance_mm: {
        type: Number,
        min: [boltHoleDistanceNmMinNum, boltHoleDistanceNMMinLength],
        max: [boltHoleDistanceNmMaxNum, boltHoleDistanceNMMaxLength],
      },
      foot_mount_hole_distance_mm: {
        type: Number,
        min: [footMountHoleDistanceNmMinNum, footMountHoleDistanceNMMinLength],
        max: [footMountHoleDistanceNmMaxNum, footMountHoleDistanceNMMaxLength],
      },
    },
    images: [
      {
        url: {
          type: String,
          minlength: [imageURLMinChar, imageURLMinLength],
          maxlength: [imageURLMaxChar, imageURLMaxLength],
        },
      },
    ],
    data_sheet_url: {
      type: String,
      minlength: [dataSheetURLMinChar, dataSheetURLMinLength],
      maxlength: [dataSheetURLMaxChar, dataSheetURLMaxLength],
    },
    created_by: {
      type: Schema.Types.ObjectId,
      required: [true, usernameRequired],
      ref: "user",
      //   validate: {
      //     validator: isActiveUserValidator,
      //     message: usernameInvalid,
      //   },
    },
    updated_by: {
      type: Schema.Types.ObjectId,
      required: [true, usernameRequired],
      ref: "user",
      //   validate: {
      //     validator: isActiveUserValidator,
      //     message: usernameInvalid,
      //   },
    },
  },
  { timestamps: { createdAt: "created_at", updatedAt: "updated_at" } }
);

motorSchema.set("toObject", { virtuals: true });
motorSchema.set("toJSON", { virtuals: true });

module.exports = mongoose.model("motor", motorSchema);
